import type { Metadata } from "next";
import "./globals.css";
import "aos/dist/aos.css";

import { AOSProvider } from "@/lib/utils/AOSProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "BookOwl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className=""
      >
         <AOSProvider />
            <ToastContainer position="top-right" autoClose={3000} />
        
        {children}
      </body>
    </html>
  );
}
